### ISSUE TITLE
[Feat] 오브젝트 클리핑

### ISSUE THREAD

**Issue by oeccsy** [Fouractal/Fermi-tale#6]
### 구현 요구사항
- Scene에 배치된 모든 오브젝트들이 주인공 캐릭터로부터 일정 거리에 포함됐을 때만 보이도록 Clip
    - Shader 사용
    - 에디터에서 6x6 만큼의 시야가 보이도록 구현
    - Rotate 되지 않은 정육면체로 구현 ( 시점의 변화가 필요 한 경우 카메라를 이용하여 구현 )

**Comment by oeccsy** [comment]
### TODO
- 디자인 팀 Material 반영 사항 확인
    - 개발팀에서 직접 Material을 커스텀 하는 작업이 필요함
    - 현재 Material에 적용되어 있는게 `색상` 말고 다른게 있는지?

**Comment by kkkkiiiiii** [comment]
###오브젝트 클리핑 최적화

- Shader의 Vector 값을 기준으로 Clip해야 함.
- 근데 실시간으로 값을 변경이 불가능함 -> Material.SetVector로 변경

모든 오브젝트에 대해 Update 돌리는 건 꽤 무거울 걸로 예상
Player 기준으로 Physics.OverlapSphere로 일정 거리 내 감지되는 오브젝트에 대해서만 Update (Material.SetVector 포함된 스크립트 활성화)

**Comment by oeccsy** [comment]
### 구현 현황

![image](https://github.com/Fouractal/Fermi-paradox/assets/77562357/2526bfa8-ecca-493e-908b-b1060543820a)
![image](https://github.com/Fouractal/Fermi-paradox/assets/77562357/e7254b87-987b-4dea-8781-793bc298c320)

- Shader에서 Clipping을 진행.
- 위의 이미지의 `PivotPoint`를 기준으로 `Cutoff Distance` 거리에 있는 부분만 렌더링
    - Material이 값 형식이기 때문에 `PivotPoint` 동기화에 어려움이 있음.
    - `PivotPoint`는 Update()에서 실시간으로 캐릭터의 위치를 받아오기로 함.
    - Material 마다 Update() 연산을 진행하기 때문에 Material이 너무 많으면 연산량에 문제가 생길 수 있을 것으로 예상함

### TODO
- 디자인 팀 Material 반영 사항 확인
    - 개발팀에서 전달받은 오브젝트의 Material을 직접 커스텀 하는 작업이 필요함
    - 현재 Material에 적용되어 있는게 `색상` 말고 다른게 있는지?

**Comment by kkkkiiiiii** [comment]
### 오브젝트 클리핑 최적화

- Shader의 Vector 값을 기준으로 Clip해야 함.
    - 근데 실시간으로 값을 변경이 불가능함 -> Material.SetVector로 변경
    
- 모든 오브젝트에 대해 Update 돌리는 건 꽤 무거울 걸로 예상
   - Player 기준으로 Physics.OverlapSphere로 일정 거리 내 감지되는 오브젝트에 대해서만 Update (Material.SetVector 포함된 스크립트 활성화)
